### ISSUE TITLE
Is there any example?

### ISSUE THREAD

**Issue by xseguib** [spatie/server-side-rendering#13]
Hi, the idea of this package looks awesome =)!, is there any example? ( I see this repo but it's empty :( https://github.com/sebastiandedeyne/laravel-server-side-rendering-examples )

Thanks!

**Comment by sebastiandedeyne** [comment]
That one shouldn't exist :) Here's the correct repo: https://github.com/spatie/laravel-server-side-rendering-examples.

Note that this uses the laravel-server-side-rendering package, which is a Laravel bridge for this package, so you'll need to go through this readme to understand how everything's set up under the hood.

I'm working on a comprehensive blogpost about this which will serve as an additional learning resource, but it's not ready yet :)

Don't be shy to open an issue if you have any further questions!
