### ISSUE TITLE
Allow context to be sent back up with `dispatch`

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/server-side-rendering#17]
The magic `dispatch` function should accept a second argument to send up context. 

Implementation idea: `dispatch` returns a JSON-serialized object, with the html in one key, and context in another.

```json
{
  "html": "....",
  "context": {
    "meta": "<meta ...>"
  }
}
```

This is a breaking change, and would change the return of `Engine::run()` from a string to an array or custom object.

See spatie/laravel-server-side-rendering#18 for a real-world use case.

**Comment by robinvdvleuten** [comment]
I desperately need it for CSS-in-JS support, where I now solve it by just letting Node.js render the complete HTML page ([webstronauts/laravel-liftoff/resources/assets/js/entry-server.js](https://github.com/webstronauts/laravel-liftoff/blob/master/resources/assets/js/entry-server.js)).

**Comment by robinvdvleuten** [comment]
I've created #19 to support this.
