### ISSUE TITLE
Usage with a Webpack Dev Server 

### ISSUE THREAD

**Issue by joshhornby** [spatie/server-side-rendering#23]
Hi,

Has anyone managed to get this package working using [Webpack Encore](https://symfony.com/doc/current/frontend.html)? I'm having issues with the `dev-server` as the file isn't technically created, but directly served from memory at the given URL instead. For example `http://localhost:8080/build/server.js`. In production it would work because you generate the files so they have a physical path on the server.

My question is has anyone got this working using a webpack dev server?

Thanks

**Comment by edcoreweb** [comment]
@joshhornby 

I think you can fake it like this:

```php
echo $renderer
    ->resolveEntryWith(function (string $entry): string {
        // here you can store the file on the server and return the path
        file_put_contents($path = 'my/server/path.js', file_get_contents($entry));
        return $path;
    })
    ->entry('http://localhost:8080/build/server.js')
    ->render();
```

**Comment by rkanagaraj** [comment]
The render not giving anything when I added store and router in my vue app
