### ISSUE TITLE
react with nextjs for async api calls

### ISSUE THREAD

**Issue by AidasK** [spatie/server-side-rendering#25]
Has anybody used next.js to render react application to string? Current approach does not work for me, because react renderToString method ignores all "fetch" requests to external apis and nextjs handles it properly. Though nextjs only works with expressjs and it does not have proper documentation for advanced usage.

**Comment by calvinchankf** [comment]
i have the same problem, did u find a way eventually?

**Comment by AidasK** [comment]
It won't work. You need to use next.js and laravel for api only.
I tried to find an easier way, but there isn't one. I wonder why react called it SSR if it only doing pre-rendering...
