### ISSUE TITLE
Root element does not get id attribute

### ISSUE THREAD

**Issue by jameswagoner** [spatie/server-side-rendering#31]
When I have a successful ssr response:

```html
<div data-server-rendered="true">
```

You still find a console error complaining about not finding `#app`.

Isn't `vue-server-renderer` supposed to add this on the root element as well?

```html
<div id="app" data-server-rendered="true">
```

**Comment by reed-jones** [comment]
No it doesn't, you need to add this to your root template yourself. https://ssr.vuejs.org/guide/hydration.html

> Note that it didn't add id="app", just the data-server-rendered attribute: you need to add the ID or some other selector to the app's root element yourself or the app won't hydrate properly.
